version: '3'
services:
  controller:
    build:
      context: .
      dockerfile: cmd/controller/Dockerfile
    ports:
      - "8085:8085"
    volumes:
      - ./configs/keys/iot.key:/keys/shared.key:ro
    networks:
      - iot
    depends_on:
      - mqttroute
    command: ["wait-for-it.sh", "mqttroute:1883", "--", "/app/controller"]

  thermostat:
    build:
      context: .
      dockerfile: cmd/smart_home_devices/thermostat/Dockerfile
    depends_on:
      - mqttroute
    volumes:
      - ./configs/keys/iot.key:/keys/shared.key:ro
    networks:
      - iot

  humidity_sensor:
    build:
      context: .
      dockerfile: cmd/smart_home_devices/humidity_sensor/Dockerfile
    volumes:
      - ./configs/keys/iot.key:/keys/shared.key:ro
    networks:
      - iot

  light_switch:
    build:
      context: .
      dockerfile: cmd/smart_home_devices/light_switch/Dockerfile
    volumes:
      - ./configs/keys/iot.key:/keys/shared.key:ro
    networks:
      - iot
  
  mqttroute:
    image: eclipse-mosquitto
    container_name: mqttroute
    ports:
      - "1883:1883"  
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - iot

  telegram_bot:
    build:
      context: .
      dockerfile: cmd/bot/Dockerfile
    depends_on:
      - mqttroute
    env_file:
      - cmd/bot/.env
    networks:
      - iot
    command: ["wait-for-it.sh", "mqttroute:1883", "--", "/app/telegram_bot"]

networks:
  iot:
