version: '3'
services:
  controller:
    build:
      context: .
      dockerfile: cmd/controller/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./configs/keys/iot.key:/keys/shared.key:ro
    networks:
      - iot
    command: ["/app/controller"]

  thermostat:
    build:
      context: .
      dockerfile: cmd/smart_home_devices/thermostat/Dockerfile
    volumes:
      - ./configs/keys/iot.key:/keys/shared.key:ro
    networks:
      - iot
    depends_on:
      - controller

  humidity_sensor:
    build:
      context: .
      dockerfile: cmd/smart_home_devices/humidity_sensor/Dockerfile
    volumes:
      - ./configs/keys/iot.key:/keys/shared.key:ro
    networks:
      - iot
    depends_on:
      - controller

  light_switch:
    build:
      context: .
      dockerfile: cmd/smart_home_devices/light_switch/Dockerfile
    volumes:
      - ./configs/keys/iot.key:/keys/shared.key:ro
    depends_on: 
      - controller
    networks:
      - iot
    

networks:
  iot:
